//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziYorumProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBlog()
        {
            this.TblYorum = new HashSet<TblYorum>();
        }
    
        public int BlogId { get; set; }
        public string BlogBaslik { get; set; }
        public string BlogIcerik { get; set; }
        public Nullable<System.DateTime> BlogTarih { get; set; }
        public string BlogGorsel { get; set; }
        public Nullable<int> BlogTur { get; set; }
        public Nullable<int> BlogKategori { get; set; }
    
        public virtual TblKategori TblKategori { get; set; }
        public virtual TblTur TblTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblYorum> TblYorum { get; set; }
    }
}
