//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziYorumProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHakkımızda
    {
        public int HakkımızdaId { get; set; }
        public string Aciklama { get; set; }
    }
}
