//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziYorumProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIletisim
    {
        public int MesajId { get; set; }
        public string AdSoyad { get; set; }
        public string Mail { get; set; }
        public string Telefon { get; set; }
        public string Konu { get; set; }
        public string MesajIcerik { get; set; }
    }
}
