//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziYorumProjesi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblYorum
    {
        public int YorumId { get; set; }
        public string Kullanici { get; set; }
        public string Mail { get; set; }
        public string YorumIcerik { get; set; }
        public Nullable<int> YorumBlog { get; set; }
    
        public virtual TblBlog TblBlog { get; set; }
    }
}
